services:
  - type: worker
    name: lgr-notif-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DISCORD_TOKEN
        fromSecret: discord-token
      - key: CLIENT_ID
        fromSecret: client-id
      - key: APIFY_TOKEN
        fromSecret: apify-token
