services:
  - type: worker
    name: lgr-notif-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DISCORD_TOKEN
        value: ${DISCORD_TOKEN}
      - key: CLIENT_ID
        value: ${CLIENT_ID}
      - key: APIFY_TOKEN
        value: ${APIFY_TOKEN}
